export const seedDatabase = [
  // DRYLAND ALTITUDE ZONE (0-1000m)
  {
    id: "sunflower-hungarian",
    name: "Sunflower",
    variety: "Hungarian White",
    kiswahili_name: "Alizeti",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "150-160 days",
    rate: "8 kg/ha",
    yield_potential: "3.5-4 tons/hectare",
    description: "Drought resilient, excellent for bird feed and oil production",
    attributes: ["Drought resilient", "Bird feed", "Oil crop"],
    planting_season: "March-May, October-November",
  },
  {
    id: "maize-ph4",
    name: "Maize",
    variety: "PH 4",
    kiswahili_name: "Mahindi",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "100-120 days",
    rate: "10 kg/ha",
    yield_potential: "26 tons/hectare",
    description: "Heat tolerant with very sweet tasting kernels, ideal for dry regions",
    attributes: ["Heat tolerant", "Sweet tasting", "High yield"],
    planting_season: "March-May, October-November",
  },
  {
    id: "fingermillet-katumani",
    name: "Finger Millet",
    variety: "Katumani",
    kiswahili_name: "Wimbi",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "75-85 days",
    rate: "10 kg/ha",
    yield_potential: "7-10 tons/hectare",
    description: "Red seeded variety, short stature, highly drought tolerant",
    attributes: ["Drought tolerant", "Short variety", "Red seeded"],
    planting_season: "March-May",
  },
  {
    id: "sorghum-standard",
    name: "Sorghum",
    variety: "Standard",
    kiswahili_name: "Mtama",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "120-150 days",
    rate: "8 kg/ha",
    yield_potential: "2-3 tons/hectare",
    description: "Drought-tolerant cereal, excellent for arid and semi-arid areas",
    attributes: ["Drought tolerant", "Arid regions", "Cereal"],
    planting_season: "March-May",
  },
  {
    id: "millet-standard",
    name: "Millet",
    variety: "Standard",
    kiswahili_name: "Wimbi",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "90-120 days",
    rate: "5 kg/ha",
    yield_potential: "1-2 tons/hectare",
    description: "Nutritious grain crop, highly drought-resistant for marginal lands",
    attributes: ["Drought resistant", "Marginal lands", "Nutritious"],
    planting_season: "March-May",
  },
  {
    id: "cowpea-standard",
    name: "Cowpea",
    variety: "Standard",
    kiswahili_name: "Maharagwe ya Maziwa",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "60-90 days",
    rate: "15 kg/ha",
    yield_potential: "1-1.5 tons/hectare",
    description: "Nitrogen-fixing legume, drought tolerant, excellent protein source",
    attributes: ["Nitrogen-fixing", "Drought tolerant", "Protein rich"],
    planting_season: "March-May, October-November",
  },

  // TRANSITIONAL ALTITUDE ZONE (1000-1500m)
  {
    id: "maize-h520",
    name: "Maize",
    variety: "H520",
    kiswahili_name: "Mahindi",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "120-150 days",
    rate: "10 kg/ha",
    yield_potential: "34 tons/hectare",
    description: "Double cobbing variety, very sweet tasting, GLS and MSV tolerant",
    attributes: ["Double cobbing", "Sweet tasting", "Disease tolerant"],
    planting_season: "March-May, October-November",
  },
  {
    id: "fingermillet-p224",
    name: "Finger Millet",
    variety: "P224",
    kiswahili_name: "Wimbi",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "90-120 days",
    rate: "10 kg/ha",
    yield_potential: "12 tons/hectare",
    description: "Malting variety, drought resistant, suitable for brewing",
    attributes: ["Malting variety", "Drought resistant", "Brewing"],
    planting_season: "March-May",
  },
  {
    id: "beans-kidney",
    name: "Beans",
    variety: "Kidney",
    kiswahili_name: "Maharagwe",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "90-120 days",
    rate: "40 kg/ha",
    yield_potential: "1.5-2.5 tons/hectare",
    description: "Nitrogen-fixing legume, excellent for soil improvement and nutrition",
    attributes: ["Nitrogen-fixing", "Soil improvement", "Protein rich"],
    planting_season: "March-May, October-November",
  },
  {
    id: "tomato-hybrid",
    name: "Tomato",
    variety: "Hybrid",
    kiswahili_name: "Nyanya",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "70-90 days",
    rate: "200 g/ha",
    yield_potential: "30-40 tons/hectare",
    description: "High-value vegetable, disease resistant, excellent market demand",
    attributes: ["High-value", "Disease resistant", "Market demand"],
    planting_season: "Year-round (with irrigation)",
  },
  {
    id: "onion-red",
    name: "Onion",
    variety: "Red",
    kiswahili_name: "Kitunguu",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "120-150 days",
    rate: "20 kg/ha",
    yield_potential: "15-25 tons/hectare",
    description: "Important spice crop with good market demand and storage properties",
    attributes: ["Spice crop", "Good storage", "Market demand"],
    planting_season: "August-October",
  },

  // MEDIUM ALTITUDE ZONE (1500-2000m)
  {
    id: "maize-aminika",
    name: "Maize",
    variety: "Aminika WH509",
    kiswahili_name: "Mahindi",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "120-140 days",
    rate: "10 kg/ha",
    yield_potential: "7-7.5 tons/hectare",
    description: "Drought tolerant, semi-flint grain, high yield potential",
    attributes: ["Drought tolerant", "Semi-flint", "High yield"],
    planting_season: "March-May, October-November",
  },
  {
    id: "potato-irish",
    name: "Potato",
    variety: "Irish",
    kiswahili_name: "Viazi",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "90-120 days",
    rate: "2000 kg/ha",
    yield_potential: "15-25 tons/hectare",
    description: "High-yielding tuber crop, excellent for food security and income",
    attributes: ["High-yielding", "Food security", "Income generation"],
    planting_season: "March-May, August-September",
  },
  {
    id: "cabbage-green",
    name: "Cabbage",
    variety: "Green",
    kiswahili_name: "Kabichi",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "90-120 days",
    rate: "300 g/ha",
    yield_potential: "25-35 tons/hectare",
    description: "Cool-season vegetable with high nutritional value and long shelf life",
    attributes: ["Cool-season", "Nutritious", "Long shelf life"],
    planting_season: "March-May, August-October",
  },
  {
    id: "carrot-orange",
    name: "Carrot",
    variety: "Orange",
    kiswahili_name: "Karanga",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "70-90 days",
    rate: "500 g/ha",
    yield_potential: "20-30 tons/hectare",
    description: "Nutritious root vegetable, good for fresh market and processing",
    attributes: ["Nutritious", "Fresh market", "Processing"],
    planting_season: "March-May, August-October",
  },
  {
    id: "spinach-green",
    name: "Spinach",
    variety: "Green",
    kiswahili_name: "Sukuma Wiki",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "45-60 days",
    rate: "5 kg/ha",
    yield_potential: "10-15 tons/hectare",
    description: "Leafy green vegetable, fast-growing, excellent nutritional value",
    attributes: ["Fast-growing", "Nutritious", "Leafy green"],
    planting_season: "Year-round",
  },
  {
    id: "peas-garden",
    name: "Garden Peas",
    variety: "Garden",
    kiswahili_name: "Njano",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "60-70 days",
    rate: "80 kg/ha",
    yield_potential: "3-4 tons/hectare",
    description: "Nitrogen-fixing legume, excellent protein source, cool-season crop",
    attributes: ["Nitrogen-fixing", "Protein rich", "Cool-season"],
    planting_season: "May-July",
  },

  // HIGHLAND ALTITUDE ZONE (2000-2500m)
  {
    id: "maize-h629",
    name: "Maize",
    variety: "H629",
    kiswahili_name: "Mahindi",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "150-210 days",
    rate: "10 kg/ha",
    yield_potential: "48 tons/hectare",
    description: "Resistant to lodging, good husk cover, excellent storage quality",
    attributes: ["Lodging resistant", "Good storage", "High yield"],
    planting_season: "March-May",
  },
  {
    id: "wheat-ks-simba",
    name: "Wheat",
    variety: "KS Simba",
    kiswahili_name: "Ngano",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "100-120 days",
    rate: "50 kg/ha",
    yield_potential: "18-22 tons/hectare",
    description: "Hard red wheat, good baking qualities, moderate rust resistance",
    attributes: ["Hard red", "Baking quality", "Rust resistant"],
    planting_season: "May-July",
  },
  {
    id: "potato-highland",
    name: "Potato",
    variety: "Highland",
    kiswahili_name: "Viazi",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "90-120 days",
    rate: "2000 kg/ha",
    yield_potential: "20-30 tons/hectare",
    description: "High-altitude adapted variety, excellent disease resistance",
    attributes: ["High-altitude adapted", "Disease resistant", "High yield"],
    planting_season: "March-May, August-September",
  },
  {
    id: "cabbage-red",
    name: "Cabbage",
    variety: "Red",
    kiswahili_name: "Kabichi Nyekundu",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "100-130 days",
    rate: "300 g/ha",
    yield_potential: "30-40 tons/hectare",
    description: "Red variety with high nutritional value, excellent storage",
    attributes: ["Red variety", "Nutritious", "Good storage"],
    planting_season: "March-May, August-October",
  },
  {
    id: "broccoli-green",
    name: "Broccoli",
    variety: "Green",
    kiswahili_name: "Broccoli",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "60-90 days",
    rate: "300 g/ha",
    yield_potential: "8-12 tons/hectare",
    description: "Cool-season cruciferous vegetable, high nutritional value",
    attributes: ["Cool-season", "Nutritious", "Cruciferous"],
    planting_season: "March-May, August-October",
  },
  {
    id: "cauliflower-white",
    name: "Cauliflower",
    variety: "White",
    kiswahili_name: "Cauliflower",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "70-100 days",
    rate: "300 g/ha",
    yield_potential: "10-15 tons/hectare",
    description: "White variety, excellent for fresh market and processing",
    attributes: ["White variety", "Fresh market", "Processing"],
    planting_season: "March-May, August-October",
  },
]

export interface Seed {
  id: string
  name: string
  variety: string
  kiswahili_name: string
  altitude_zone: string
  min_altitude: number
  max_altitude: number
  maturity: string
  rate: string
  yield_potential: string
  description: string
  attributes: string[]
  planting_season: string
}

export function getRecommendedSeeds(altitude: number): Seed[] {
  return seedDatabase
    .filter((seed) => altitude >= seed.min_altitude && altitude <= seed.max_altitude)
    .sort((a, b) => {
      const aMid = (a.min_altitude + a.max_altitude) / 2
      const bMid = (b.min_altitude + b.max_altitude) / 2
      return Math.abs(altitude - aMid) - Math.abs(altitude - bMid)
    })
}
