export const seedDatabase = [
  // DRYLAND ALTITUDE ZONE (0-1000m)
  // Cereals
  {
    id: "maize-ph4",
    name: "Maize",
    variety: "PH 4",
    kiswahili_name: "Mahindi",
    french_name: "Maïs",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "100-120 days",
    rate: "10 kg/ha",
    yield_potential: "26 tons/hectare",
    description:
      "Heat tolerant with very sweet tasting kernels, ideal for dry regions. Excellent for fresh market and processing.",
    detailed_info:
      "PH 4 is a hybrid maize variety specifically bred for hot, dry climates. It has strong root systems that penetrate deep into soil to access moisture. The kernels are exceptionally sweet, making it popular for fresh consumption. Resistant to common maize diseases including Gray Leaf Spot and Maize Streak Virus.",
    attributes: ["Heat tolerant", "Sweet tasting", "High yield", "Disease resistant"],
    planting_season: "March-May, October-November",
    soil_type: "Well-drained sandy loam",
    water_requirement: "Low to moderate",
    pest_management: "Watch for fall armyworm, stem borers",
    disease_management: "Resistant to GLS and MSV",
    storage_life: "6-8 months in cool, dry conditions",
  },
  {
    id: "sorghum-standard",
    name: "Sorghum",
    variety: "Standard",
    kiswahili_name: "Mtama",
    french_name: "Sorgho",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "120-150 days",
    rate: "8 kg/ha",
    yield_potential: "2-3 tons/hectare",
    description: "Drought-tolerant cereal, excellent for arid and semi-arid areas. Can survive with minimal water.",
    detailed_info:
      "Sorghum is one of the most drought-tolerant cereals available. It has deep root systems and waxy leaf coating that reduces water loss. Suitable for marginal lands where other crops fail. Can be used for grain, animal feed, or silage.",
    attributes: ["Drought tolerant", "Arid regions", "Cereal", "Animal feed"],
    planting_season: "March-May",
    soil_type: "Any soil type",
    water_requirement: "Very low",
    pest_management: "Relatively pest-free",
    disease_management: "Generally disease-resistant",
    storage_life: "12+ months",
  },
  {
    id: "millet-standard",
    name: "Millet",
    variety: "Standard",
    kiswahili_name: "Wimbi",
    french_name: "Millet",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "90-120 days",
    rate: "5 kg/ha",
    yield_potential: "1-2 tons/hectare",
    description: "Nutritious grain crop, highly drought-resistant for marginal lands. Rich in minerals and protein.",
    detailed_info:
      "Millet is a nutritious ancient grain with high protein content. It's extremely drought-resistant and can grow in poor soils. Rich in iron, magnesium, and phosphorus. Excellent for food security in arid regions.",
    attributes: ["Drought resistant", "Marginal lands", "Nutritious", "Ancient grain"],
    planting_season: "March-May",
    soil_type: "Poor to moderate soils",
    water_requirement: "Very low",
    pest_management: "Minimal pest issues",
    disease_management: "Disease-resistant",
    storage_life: "12+ months",
  },
  {
    id: "fingermillet-katumani",
    name: "Finger Millet",
    variety: "Katumani",
    kiswahili_name: "Wimbi",
    french_name: "Millet des Doigts",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "75-85 days",
    rate: "10 kg/ha",
    yield_potential: "7-10 tons/hectare",
    description: "Red seeded variety, short stature, highly drought tolerant. Excellent nutritional profile.",
    detailed_info:
      "Finger millet (Eleusine coracana) is a highly nutritious grain with excellent calcium content. The red seeds are rich in antioxidants. Short stature makes it suitable for intercropping. Can be used for porridge, flour, or animal feed.",
    attributes: ["Drought tolerant", "Short variety", "Red seeded", "High calcium"],
    planting_season: "March-May",
    soil_type: "Well-drained loam",
    water_requirement: "Low",
    pest_management: "Relatively pest-free",
    disease_management: "Disease-resistant",
    storage_life: "12+ months",
  },

  // Legumes
  {
    id: "cowpea-standard",
    name: "Cowpea",
    variety: "Standard",
    kiswahili_name: "Maharagwe ya Maziwa",
    french_name: "Niébé",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "60-90 days",
    rate: "15 kg/ha",
    yield_potential: "1-1.5 tons/hectare",
    description: "Nitrogen-fixing legume, drought tolerant, excellent protein source. Improves soil fertility.",
    detailed_info:
      "Cowpea is a versatile legume that fixes nitrogen in soil, improving fertility for subsequent crops. Drought-tolerant and can grow in poor soils. Both pods and leaves are edible. Excellent protein source for human consumption and animal feed.",
    attributes: ["Nitrogen-fixing", "Drought tolerant", "Protein rich", "Soil improvement"],
    planting_season: "March-May, October-November",
    soil_type: "Any soil type",
    water_requirement: "Low to moderate",
    pest_management: "Watch for bruchids in storage",
    disease_management: "Generally disease-resistant",
    storage_life: "8-12 months",
  },
  {
    id: "groundnut-spanish",
    name: "Groundnut",
    variety: "Spanish",
    kiswahili_name: "Karanga",
    french_name: "Arachide",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "120-150 days",
    rate: "40 kg/ha",
    yield_potential: "1.5-2.5 tons/hectare",
    description: "Oil crop with high protein content. Nitrogen-fixing legume for soil improvement.",
    detailed_info:
      "Groundnuts are an important cash crop and protein source. Spanish variety has small pods but high oil content. Nitrogen-fixing properties improve soil fertility. Can be used for oil extraction, human consumption, or animal feed.",
    attributes: ["Oil crop", "Protein rich", "Nitrogen-fixing", "Cash crop"],
    planting_season: "March-May",
    soil_type: "Well-drained sandy loam",
    water_requirement: "Moderate",
    pest_management: "Watch for aflatoxin contamination",
    disease_management: "Resistant to leaf spot",
    storage_life: "6-8 months",
  },

  // Oil crops
  {
    id: "sunflower-hungarian",
    name: "Sunflower",
    variety: "Hungarian White",
    kiswahili_name: "Alizeti",
    french_name: "Tournesol",
    altitude_zone: "Dryland Altitude",
    min_altitude: 0,
    max_altitude: 1000,
    maturity: "150-160 days",
    rate: "8 kg/ha",
    yield_potential: "3.5-4 tons/hectare",
    description: "Drought resilient, excellent for bird feed and oil production. High oil content.",
    detailed_info:
      "Sunflower is a drought-tolerant oil crop with high oil content (40-50%). The seeds are excellent for bird feed and human consumption. Tall plants can provide shade for intercropping. Allelopathic properties help suppress weeds.",
    attributes: ["Drought resilient", "Bird feed", "Oil crop", "High yield"],
    planting_season: "March-May, October-November",
    soil_type: "Well-drained loam",
    water_requirement: "Low to moderate",
    pest_management: "Watch for sunflower beetles",
    disease_management: "Resistant to most diseases",
    storage_life: "12+ months",
  },

  // TRANSITIONAL ALTITUDE ZONE (1000-1500m)
  {
    id: "maize-h520",
    name: "Maize",
    variety: "H520",
    kiswahili_name: "Mahindi",
    french_name: "Maïs",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "120-150 days",
    rate: "10 kg/ha",
    yield_potential: "34 tons/hectare",
    description: "Double cobbing variety, very sweet tasting, GLS and MSV tolerant. Excellent for fresh market.",
    detailed_info:
      "H520 is a premium hybrid maize with exceptional sweetness and double cobs. Highly resistant to Gray Leaf Spot and Maize Streak Virus. Excellent for fresh market sales and processing. Strong stalks resist lodging.",
    attributes: ["Double cobbing", "Sweet tasting", "Disease tolerant", "High yield"],
    planting_season: "March-May, October-November",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Resistant to common pests",
    disease_management: "GLS and MSV resistant",
    storage_life: "6-8 months",
  },
  {
    id: "beans-kidney",
    name: "Beans",
    variety: "Kidney",
    kiswahili_name: "Maharagwe",
    french_name: "Haricots",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "90-120 days",
    rate: "40 kg/ha",
    yield_potential: "1.5-2.5 tons/hectare",
    description: "Nitrogen-fixing legume, excellent for soil improvement and nutrition. High market demand.",
    detailed_info:
      "Kidney beans are a staple protein source with excellent nutritional profile. Nitrogen-fixing properties improve soil fertility. Can be intercropped with maize. High market demand in urban areas.",
    attributes: ["Nitrogen-fixing", "Soil improvement", "Protein rich", "Market demand"],
    planting_season: "March-May, October-November",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Watch for bean flies",
    disease_management: "Resistant to common diseases",
    storage_life: "12+ months",
  },
  {
    id: "tomato-hybrid",
    name: "Tomato",
    variety: "Hybrid",
    kiswahili_name: "Nyanya",
    french_name: "Tomate",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "70-90 days",
    rate: "200 g/ha",
    yield_potential: "30-40 tons/hectare",
    description: "High-value vegetable, disease resistant, excellent market demand. Suitable for irrigation.",
    detailed_info:
      "Hybrid tomatoes offer superior disease resistance and consistent yields. High market value makes them excellent for income generation. Requires irrigation for optimal production. Can be grown year-round with proper management.",
    attributes: ["High-value", "Disease resistant", "Market demand", "High yield"],
    planting_season: "Year-round (with irrigation)",
    soil_type: "Rich loam with organic matter",
    water_requirement: "High (irrigation needed)",
    pest_management: "Watch for whiteflies and spider mites",
    disease_management: "Resistant to late blight and early blight",
    storage_life: "2-3 weeks at room temperature",
  },
  {
    id: "onion-red",
    name: "Onion",
    variety: "Red",
    kiswahili_name: "Kitunguu",
    french_name: "Oignon",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "120-150 days",
    rate: "20 kg/ha",
    yield_potential: "15-25 tons/hectare",
    description: "Important spice crop with good market demand and storage properties. High income potential.",
    detailed_info:
      "Red onions are an important spice crop with excellent storage properties. High market demand in urban areas. Can be stored for several months. Requires good soil preparation and consistent watering.",
    attributes: ["Spice crop", "Good storage", "Market demand", "Income generation"],
    planting_season: "August-October",
    soil_type: "Well-prepared loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for onion flies",
    disease_management: "Resistant to most diseases",
    storage_life: "4-6 months",
  },
  {
    id: "pepper-bell",
    name: "Bell Pepper",
    variety: "Hybrid",
    kiswahili_name: "Pilipili",
    french_name: "Poivron",
    altitude_zone: "Transitional Altitude",
    min_altitude: 1000,
    max_altitude: 1500,
    maturity: "90-120 days",
    rate: "300 g/ha",
    yield_potential: "20-30 tons/hectare",
    description: "High-value vegetable with excellent market demand. Multiple colors available.",
    detailed_info:
      "Bell peppers are high-value vegetables with strong market demand. Available in red, yellow, and green colors. Requires warm conditions and consistent watering. Excellent for fresh market and processing.",
    attributes: ["High-value", "Market demand", "Multiple colors", "High yield"],
    planting_season: "Year-round (with irrigation)",
    soil_type: "Rich loam",
    water_requirement: "High",
    pest_management: "Watch for spider mites",
    disease_management: "Resistant to common diseases",
    storage_life: "2-3 weeks",
  },

  // MEDIUM ALTITUDE ZONE (1500-2000m)
  {
    id: "maize-aminika",
    name: "Maize",
    variety: "Aminika WH509",
    kiswahili_name: "Mahindi",
    french_name: "Maïs",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "120-140 days",
    rate: "10 kg/ha",
    yield_potential: "7-7.5 tons/hectare",
    description: "Drought tolerant, semi-flint grain, high yield potential. Excellent for medium altitudes.",
    detailed_info:
      "Aminika WH509 is specifically bred for medium altitude zones. Semi-flint grain is excellent for storage and milling. Drought-tolerant with strong root systems. Good disease resistance.",
    attributes: ["Drought tolerant", "Semi-flint", "High yield", "Medium altitude"],
    planting_season: "March-May, October-November",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Resistant to common pests",
    disease_management: "Good disease resistance",
    storage_life: "12+ months",
  },
  {
    id: "potato-irish",
    name: "Potato",
    variety: "Irish",
    kiswahili_name: "Viazi",
    french_name: "Pomme de Terre",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "90-120 days",
    rate: "2000 kg/ha",
    yield_potential: "15-25 tons/hectare",
    description: "High-yielding tuber crop, excellent for food security and income. Versatile crop.",
    detailed_info:
      "Irish potatoes are high-yielding and versatile. Can be used for fresh consumption, processing, or animal feed. Requires good soil preparation and consistent watering. Excellent for food security and income generation.",
    attributes: ["High-yielding", "Food security", "Income generation", "Versatile"],
    planting_season: "March-May, August-September",
    soil_type: "Well-drained loam",
    water_requirement: "High",
    pest_management: "Watch for late blight",
    disease_management: "Resistant to common diseases",
    storage_life: "3-4 months",
  },
  {
    id: "cabbage-green",
    name: "Cabbage",
    variety: "Green",
    kiswahili_name: "Kabichi",
    french_name: "Chou",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "90-120 days",
    rate: "300 g/ha",
    yield_potential: "25-35 tons/hectare",
    description: "Cool-season vegetable with high nutritional value and long shelf life. Excellent storage.",
    detailed_info:
      "Green cabbage is a cool-season vegetable with excellent nutritional value. Long shelf life makes it suitable for storage and transport. Can be used fresh or processed. High market demand.",
    attributes: ["Cool-season", "Nutritious", "Long shelf life", "High yield"],
    planting_season: "March-May, August-October",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for cabbage worms",
    disease_management: "Resistant to common diseases",
    storage_life: "2-3 months",
  },
  {
    id: "carrot-orange",
    name: "Carrot",
    variety: "Orange",
    kiswahili_name: "Karanga",
    french_name: "Carotte",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "70-90 days",
    rate: "500 g/ha",
    yield_potential: "20-30 tons/hectare",
    description: "Nutritious root vegetable, good for fresh market and processing. Rich in beta-carotene.",
    detailed_info:
      "Orange carrots are rich in beta-carotene and other nutrients. Excellent for fresh market and processing. Good storage properties. Can be used for juice, canning, or fresh consumption.",
    attributes: ["Nutritious", "Fresh market", "Processing", "Good storage"],
    planting_season: "March-May, August-October",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Relatively pest-free",
    disease_management: "Disease-resistant",
    storage_life: "3-4 months",
  },
  {
    id: "spinach-green",
    name: "Spinach",
    variety: "Green",
    kiswahili_name: "Sukuma Wiki",
    french_name: "Épinard",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "45-60 days",
    rate: "5 kg/ha",
    yield_potential: "10-15 tons/hectare",
    description: "Leafy green vegetable, fast-growing, excellent nutritional value. Year-round production.",
    detailed_info:
      "Spinach is a fast-growing leafy green with excellent nutritional value. Rich in iron and other minerals. Can be harvested continuously. Excellent for fresh market and processing.",
    attributes: ["Fast-growing", "Nutritious", "Leafy green", "Year-round"],
    planting_season: "Year-round",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Relatively pest-free",
    disease_management: "Disease-resistant",
    storage_life: "1-2 weeks",
  },
  {
    id: "peas-garden",
    name: "Garden Peas",
    variety: "Garden",
    kiswahili_name: "Njano",
    french_name: "Pois",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "60-70 days",
    rate: "80 kg/ha",
    yield_potential: "3-4 tons/hectare",
    description: "Nitrogen-fixing legume, excellent protein source, cool-season crop. High market value.",
    detailed_info:
      "Garden peas are a cool-season legume with excellent nutritional profile. Nitrogen-fixing properties improve soil fertility. High market demand for fresh and frozen peas. Can be intercropped with other vegetables.",
    attributes: ["Nitrogen-fixing", "Protein rich", "Cool-season", "Market demand"],
    planting_season: "May-July",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Watch for pea beetles",
    disease_management: "Resistant to common diseases",
    storage_life: "1-2 weeks fresh, 12+ months frozen",
  },
  {
    id: "lettuce-green",
    name: "Lettuce",
    variety: "Green",
    kiswahili_name: "Saladi",
    french_name: "Laitue",
    altitude_zone: "Medium Altitude",
    min_altitude: 1500,
    max_altitude: 2000,
    maturity: "45-60 days",
    rate: "3 kg/ha",
    yield_potential: "8-12 tons/hectare",
    description: "Cool-season leafy vegetable, fast-growing, excellent for fresh market. High nutritional value.",
    detailed_info:
      "Lettuce is a fast-growing cool-season vegetable with excellent nutritional value. Can be harvested continuously. Excellent for fresh market and salads. Multiple varieties available.",
    attributes: ["Cool-season", "Fast-growing", "Fresh market", "Nutritious"],
    planting_season: "March-May, August-October",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for aphids",
    disease_management: "Resistant to common diseases",
    storage_life: "1-2 weeks",
  },

  // HIGHLAND ALTITUDE ZONE (2000-2500m)
  {
    id: "maize-h629",
    name: "Maize",
    variety: "H629",
    kiswahili_name: "Mahindi",
    french_name: "Maïs",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "150-210 days",
    rate: "10 kg/ha",
    yield_potential: "48 tons/hectare",
    description: "Resistant to lodging, good husk cover, excellent storage quality. High altitude adapted.",
    detailed_info:
      "H629 is specifically bred for high altitude zones. Resistant to lodging with strong stalks. Good husk cover protects grain from weather. Excellent storage quality. High yield potential.",
    attributes: ["Lodging resistant", "Good storage", "High yield", "High altitude"],
    planting_season: "March-May",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Resistant to common pests",
    disease_management: "Good disease resistance",
    storage_life: "12+ months",
  },
  {
    id: "wheat-ks-simba",
    name: "Wheat",
    variety: "KS Simba",
    kiswahili_name: "Ngano",
    french_name: "Blé",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "100-120 days",
    rate: "50 kg/ha",
    yield_potential: "18-22 tons/hectare",
    description: "Hard red wheat, good baking qualities, moderate rust resistance. Excellent for flour.",
    detailed_info:
      "KS Simba is a hard red wheat with excellent baking qualities. Moderate rust resistance. Suitable for flour production and bread making. High market demand.",
    attributes: ["Hard red", "Baking quality", "Rust resistant", "High yield"],
    planting_season: "May-July",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Relatively pest-free",
    disease_management: "Rust resistant",
    storage_life: "12+ months",
  },
  {
    id: "potato-highland",
    name: "Potato",
    variety: "Highland",
    kiswahili_name: "Viazi",
    french_name: "Pomme de Terre",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "90-120 days",
    rate: "2000 kg/ha",
    yield_potential: "20-30 tons/hectare",
    description: "High-altitude adapted variety, excellent disease resistance. Superior quality tubers.",
    detailed_info:
      "Highland potatoes are specifically adapted to high altitude conditions. Excellent disease resistance. Superior quality tubers with excellent storage properties. High yield potential.",
    attributes: ["High-altitude adapted", "Disease resistant", "High yield", "Good storage"],
    planting_season: "March-May, August-September",
    soil_type: "Well-drained loam",
    water_requirement: "High",
    pest_management: "Resistant to common pests",
    disease_management: "Excellent disease resistance",
    storage_life: "4-6 months",
  },
  {
    id: "cabbage-red",
    name: "Cabbage",
    variety: "Red",
    kiswahili_name: "Kabichi Nyekundu",
    french_name: "Chou Rouge",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "100-130 days",
    rate: "300 g/ha",
    yield_potential: "30-40 tons/hectare",
    description: "Red variety with high nutritional value, excellent storage. Rich in anthocyanins.",
    detailed_info:
      "Red cabbage is rich in anthocyanins and other antioxidants. Excellent storage properties. High market demand. Can be used fresh or processed.",
    attributes: ["Red variety", "Nutritious", "Good storage", "High yield"],
    planting_season: "March-May, August-October",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for cabbage worms",
    disease_management: "Resistant to common diseases",
    storage_life: "3-4 months",
  },
  {
    id: "broccoli-green",
    name: "Broccoli",
    variety: "Green",
    kiswahili_name: "Broccoli",
    french_name: "Brocoli",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "60-90 days",
    rate: "300 g/ha",
    yield_potential: "8-12 tons/hectare",
    description: "Cool-season cruciferous vegetable, high nutritional value. Excellent for fresh market.",
    detailed_info:
      "Broccoli is a cool-season vegetable with excellent nutritional value. Rich in vitamins and minerals. High market demand. Can be used fresh or processed.",
    attributes: ["Cool-season", "Nutritious", "Cruciferous", "Market demand"],
    planting_season: "March-May, August-October",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for cabbage worms",
    disease_management: "Resistant to common diseases",
    storage_life: "1-2 weeks",
  },
  {
    id: "cauliflower-white",
    name: "Cauliflower",
    variety: "White",
    kiswahili_name: "Cauliflower",
    french_name: "Chou-fleur",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "70-100 days",
    rate: "300 g/ha",
    yield_potential: "10-15 tons/hectare",
    description: "White variety, excellent for fresh market and processing. High nutritional value.",
    detailed_info:
      "Cauliflower is a cool-season vegetable with excellent nutritional value. White variety is popular in fresh market. Can be used fresh or processed. High market demand.",
    attributes: ["White variety", "Fresh market", "Processing", "Nutritious"],
    planting_season: "March-May, August-October",
    soil_type: "Rich loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for cabbage worms",
    disease_management: "Resistant to common diseases",
    storage_life: "1-2 weeks",
  },
  {
    id: "bean-french",
    name: "French Beans",
    variety: "Green",
    kiswahili_name: "Maharagwe ya Kijani",
    french_name: "Haricots Verts",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "50-60 days",
    rate: "30 kg/ha",
    yield_potential: "8-12 tons/hectare",
    description: "High-value vegetable, excellent for export market. Tender green pods.",
    detailed_info:
      "French beans are high-value vegetables with strong export market demand. Tender green pods are harvested before maturity. Nitrogen-fixing properties improve soil fertility. Excellent income source.",
    attributes: ["High-value", "Export market", "Nitrogen-fixing", "Income generation"],
    planting_season: "March-May, August-October",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate to high",
    pest_management: "Watch for bean flies",
    disease_management: "Resistant to common diseases",
    storage_life: "1-2 weeks",
  },
  {
    id: "avocado-hass",
    name: "Avocado",
    variety: "Hass",
    kiswahili_name: "Avokado",
    french_name: "Avocat",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "3-4 years to first harvest",
    rate: "200-250 trees/ha",
    yield_potential: "10-15 tons/hectare",
    description: "High-value perennial crop, excellent market demand. Long productive life.",
    detailed_info:
      "Hass avocados are high-value perennial crops with excellent market demand. Trees are productive for 20+ years. Requires good soil and consistent watering. Excellent long-term income source.",
    attributes: ["High-value", "Perennial", "Market demand", "Long productive life"],
    planting_season: "Year-round",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate to high",
    pest_management: "Relatively pest-free",
    disease_management: "Disease-resistant",
    storage_life: "2-3 weeks",
  },
  {
    id: "apple-red",
    name: "Apple",
    variety: "Red Delicious",
    kiswahili_name: "Tufaha",
    french_name: "Pomme",
    altitude_zone: "Highland Altitude",
    min_altitude: 2000,
    max_altitude: 2500,
    maturity: "2-3 years to first harvest",
    rate: "200-250 trees/ha",
    yield_potential: "15-20 tons/hectare",
    description: "High-value perennial crop, excellent for fresh market. Long productive life.",
    detailed_info:
      "Red Delicious apples are high-value fruits with excellent market demand. Trees are productive for 20+ years. Requires cool climate and good soil. Excellent long-term income source.",
    attributes: ["High-value", "Perennial", "Fresh market", "Long productive life"],
    planting_season: "Year-round",
    soil_type: "Well-drained loam",
    water_requirement: "Moderate",
    pest_management: "Watch for apple scab",
    disease_management: "Resistant to common diseases",
    storage_life: "3-4 months",
  },
]

export interface Seed {
  id: string
  name: string
  variety: string
  kiswahili_name: string
  french_name: string
  altitude_zone: string
  min_altitude: number
  max_altitude: number
  maturity: string
  rate: string
  yield_potential: string
  description: string
  detailed_info: string
  attributes: string[]
  planting_season: string
  soil_type: string
  water_requirement: string
  pest_management: string
  disease_management: string
  storage_life: string
}

export function getRecommendedSeeds(altitude: number): Seed[] {
  return seedDatabase
    .filter((seed) => altitude >= seed.min_altitude && altitude <= seed.max_altitude)
    .sort((a, b) => {
      const aMid = (a.min_altitude + a.max_altitude) / 2
      const bMid = (b.min_altitude + b.max_altitude) / 2
      return Math.abs(altitude - aMid) - Math.abs(altitude - bMid)
    })
}
